-- entities for residents
TRUNCATE TABLE suits RESTART IDENTITY CASCADE;
TRUNCATE TABLE sexes RESTART IDENTITY CASCADE;
TRUNCATE TABLE roles RESTART IDENTITY CASCADE;

TRUNCATE TABLE residents RESTART IDENTITY CASCADE;
TRUNCATE TABLE gaits RESTART IDENTITY CASCADE;
TRUNCATE TABLE kingdoms RESTART IDENTITY CASCADE;

TRUNCATE TABLE registrations RESTART IDENTITY CASCADE;


TRUNCATE TABLE residences RESTART IDENTITY CASCADE;


-- entities for clothes
TRUNCATE TABLE types RESTART IDENTITY CASCADE;
TRUNCATE TABLE colours RESTART IDENTITY CASCADE;
TRUNCATE TABLE patterns RESTART IDENTITY CASCADE;

TRUNCATE TABLE clothes RESTART IDENTITY CASCADE;


TRUNCATE TABLE crowns RESTART IDENTITY CASCADE;



TRUNCATE TABLE leaders RESTART IDENTITY CASCADE;


TRUNCATE TABLE worships RESTART IDENTITY CASCADE;


TRUNCATE TABLE tools RESTART IDENTITY CASCADE;


TRUNCATE TABLE weapons RESTART IDENTITY CASCADE;
