-- entities for residents
DROP TABLE IF EXISTS suits CASCADE;
DROP TABLE IF EXISTS sexes CASCADE;
DROP TABLE IF EXISTS roles CASCADE;

DROP TABLE IF EXISTS residents CASCADE;
DROP TABLE IF EXISTS gaits CASCADE;


DROP TABLE IF EXISTS registrations CASCADE;


DROP TABLE IF EXISTS residences CASCADE;


-- entities for clothes
DROP TABLE IF EXISTS types CASCADE;
DROP TABLE IF EXISTS colours CASCADE;
DROP TABLE IF EXISTS patterns CASCADE;

DROP TABLE IF EXISTS clothes CASCADE;


DROP TABLE IF EXISTS crowns CASCADE;


DROP TABLE IF EXISTS kingdoms CASCADE;


DROP TABLE IF EXISTS leaders CASCADE;


DROP TABLE IF EXISTS worships CASCADE;


DROP TABLE IF EXISTS tools CASCADE;


DROP TABLE IF EXISTS weapons CASCADE;